const BUTTON_VARIANT_NORMAL = 'normal';
const BUTTON_VARIANT_VERY_BIG = 'very-big';
const BUTTON_VARIANT_SMALL ='small';
const BUTTON_THEME_OUTLINE = 'outline';
const BUTTON_THEME_FILLED = 'filled';

export { BUTTON_VARIANT_NORMAL,BUTTON_VARIANT_VERY_BIG, BUTTON_VARIANT_SMALL, BUTTON_THEME_OUTLINE, BUTTON_THEME_FILLED };
